# Site
name: "Grain de Sable et Pomme de Pin"
title: "Grain de Sable et Pomme de Pin"
description: "L'association Grain de Sable et Pomme de Pin a pour but de protéger l'environnement, tout particulièrement les espaces naturels, de défendre le cadre de vie des habitants et de promouvoir le développement durable."
logo: 'assets/images/logo-gspp.png'
favicon: 'assets/images/logo-gspp.png'
baseurl: /
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  gspp:
    name: GSPP
    display_name: gspp
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: wowthemesnet@gmail.com
    web: https://gspp.asso.st
    twitter: 
    description: "Grain de Sable et Pomme de Pin"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: GFM


# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      path: "pdf"
    values:
      pdf: true

